name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Ще се стартира при push към main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Това дава write permissions на id-token

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish the application
      run: dotnet publish -c Release -o ./publish

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}  # ID на клиент приложението
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}  # ID на Azure Directory
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}  # Секрет на клиента
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # ID на абонамент

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'contactssinsanewebapp'  # Името на твоето Azure App Service
        package: ./publish  # Пътя към публикуваното приложение
