name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Ще се стартира при push към main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish the application
      run: dotnet publish -c Release -o ./publish

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ad61c955-7aa0-410b-996d-42100d971f5d   # ID на клиент приложението
        tenant-id: 4a06d40c-e447-42be-baef-dd0421ed10bd  # ID на Azure Directory
        client-secret: 90d8cc98-aa15-4ddb-92c1-6f96dbc960dd  # Секрет на клиента
        subscription-id: e0884437-ea81-4f84-ab19-b665093af74e  # ID на абонамент

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'contactssinsanewebapp'  # Името на твоето Azure App Service
        package: ./publish  # Пътя към публикуваното приложение

