name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Ще се стартира при push към main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish the application
      run: dotnet publish -c Release -o ./publish

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: e9c42be3-13a6-4e23-9cd4-7204e062aaa9  # Вашият Client ID
        tenant-id: 4a06d40c-e447-42be-baef-dd0421ed10bd  # Вашият Tenant ID
        client-secret: f69590f7-0c32-441c-a8ec-e5bcf51fa9b6  # Вашият Client Secret
        subscription-id: e0884437-ea81-4f84-ab19-b665093af74e  # ЗАМЕНИ с реалния subscription ID
        auth-type: servicePrincipal 

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'contactssinsanewebapp'  # Името на твоето Azure App Service
        package: ./publish  # Пътя към публикуваното приложение
