name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Ще се стартира при push към main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish the application
      run: dotnet publish -c Release -o ./publish

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: e9c42be3-13a6-4e23-9cd4-7204e062aaa9  # ID на клиент приложението
        tenant-id: 3fe7e15c-d999-46ef-bf4e-9887aeb3b7b2  # ID на Azure Directory
        client-secret: 4a06d40c-e447-42be-baef-dd0421ed10bd  # Секрет на клиента

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'contactssinsanewebapp'  # Името на твоето Azure App Service
        publish-profile: <publishData><publishProfile profileName="contactssinsanewebapp - Web Deploy" publishMethod="MSDeploy" publishUrl="contactssinsanewebapp.scm.azurewebsites.net:443" msdeploySite="contactssinsanewebapp" userName="$contactssinsanewebapp" userPWD="t4Cua62TxPw9KP6CssTKrbZ5vs3b1nNCYmsZRZCPY46ExGA8bBHfoeowonLK" destinationAppUrl="http://contactssinsanewebapp.azurewebsites.net" SQLServerDBConnectionString="Data Source=tcp:contacsqlserver.database.windows.net,1433;Initial Catalog=Contactsdb;User ID=adminuser;Password=P@ssw0rd1234;Trusted_Connection=False;MultipleActiveResultSets=True;" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites" targetDatabaseEngineType="sqlazuredatabase" targetServerVersion="Version100"><databases><add name="DefaultConnection" connectionString="Data Source=tcp:contacsqlserver.database.windows.net,1433;Initial Catalog=Contactsdb;User ID=adminuser;Password=P@ssw0rd1234;Trusted_Connection=False;MultipleActiveResultSets=True;" providerName="System.Data.SqlClient" type="Sql" targetDatabaseEngineType="sqlazuredatabase" targetServerVersion="Version100" /></databases></publishProfile><publishProfile profileName="contactssinsanewebapp - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod-db3-177.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="contactssinsanewebapp\$contactssinsanewebapp" userPWD="t4Cua62TxPw9KP6CssTKrbZ5vs3b1nNCYmsZRZCPY46ExGA8bBHfoeowonLK" destinationAppUrl="http://contactssinsanewebapp.azurewebsites.net" SQLServerDBConnectionString="Data Source=tcp:contacsqlserver.database.windows.net,1433;Initial Catalog=Contactsdb;User ID=adminuser;Password=P@ssw0rd1234;Trusted_Connection=False;MultipleActiveResultSets=True;" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites" targetDatabaseEngineType="sqlazuredatabase" targetServerVersion="Version100"><databases><add name="DefaultConnection" connectionString="Data Source=tcp:contacsqlserver.database.windows.net,1433;Initial Catalog=Contactsdb;User ID=adminuser;Password=P@ssw0rd1234;Trusted_Connection=False;MultipleActiveResultSets=True;" providerName="System.Data.SqlClient" type="Sql" targetDatabaseEngineType="sqlazuredatabase" targetServerVersion="Version100" /></databases></publishProfile><publishProfile profileName="contactssinsanewebapp - Zip Deploy" publishMethod="ZipDeploy" publishUrl="contactssinsanewebapp.scm.azurewebsites.net:443" userName="$contactssinsanewebapp" userPWD="t4Cua62TxPw9KP6CssTKrbZ5vs3b1nNCYmsZRZCPY46ExGA8bBHfoeowonLK" destinationAppUrl="http://contactssinsanewebapp.azurewebsites.net" SQLServerDBConnectionString="Data Source=tcp:contacsqlserver.database.windows.net,1433;Initial Catalog=Contactsdb;User ID=adminuser;Password=P@ssw0rd1234;Trusted_Connection=False;MultipleActiveResultSets=True;" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites" targetDatabaseEngineType="sqlazuredatabase" targetServerVersion="Version100"><databases><add name="DefaultConnection" connectionString="Data Source=tcp:contacsqlserver.database.windows.net,1433;Initial Catalog=Contactsdb;User ID=adminuser;Password=P@ssw0rd1234;Trusted_Connection=False;MultipleActiveResultSets=True;" providerName="System.Data.SqlClient" type="Sql" targetDatabaseEngineType="sqlazuredatabase" targetServerVersion="Version100" /></databases></publishProfile></publishData>  # Публикационният профил
        package: ./publish
